server:
  port: 7077

spring:
  kafka:
    bootstrap-servers: localhost:29092
  cloud:
      kafka:
        binder:
          brokers: localhost:29092
      stream:
        bindings:
          new-transaction-input-channel:
            destination: new-transaction
#          valid-transaction-output-channel:
#            destination: valid-transaction
#          invalid-transaction-output-channel:
#            destination: invalid-transaction
